### ISSUE TITLE
Ubuntu20.04无法应用生成的libyolov5.so库

### ISSUE THREAD

**Issue by feizhufanfan** [ncdhz/YoloV5-LibTorch#11]
编译环境
Ubuntu 20.04 
gcc-5
cmake 3.21.3
cuda:10.2
cudnn:8.2.1
pytorch：libtorch-shared-with-deps-1.9.1+cu102
opencv：4.5.3 

> -- Found CUDA: /usr/local/cuda (found suitable exact version "10.2") 
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.2.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  5.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50
-- Found CUDA: /usr/local/cuda (found suitable exact version "10.2") 
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v8.2.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  5.0
-- Added CUDA NVCC flags for: -gencode;arch=compute_50,code=sm_50
-- Configuring done
-- Generating done
-- Build files have been written to: /home/du/SoftWave/Project/YoloV5-LibTorch/cmake-build-debug

生成test的过程中，libyolov5.so正常生成但连接到test时导致opencv库引用失败。

> /home/du/SoftWave/clion-2021.2.2/bin/cmake/linux/bin/cmake --build /home/du/SoftWave/Project/YoloV5-LibTorch/cmake-build-debug --target test -- -j 3
Scanning dependencies of target YoloV5
[ 25%] Building CXX object src/CMakeFiles/YoloV5.dir/YoloV5.cpp.o
/home/du/SoftWave/Project/YoloV5-LibTorch/src/YoloV5.cpp: In member function ‘cv::Mat YoloV5::drawRectangle(cv::Mat, at::Tensor, std::map<int, cv::Scalar_<double> >, std::map<int, std::basic_string<char> >, int)’:
/home/du/SoftWave/Project/YoloV5-LibTorch/src/YoloV5.cpp:321:22: warning: passing NULL to non-pointer argument 1 of ‘cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]’ [-Wconversion-null]
   cv::Scalar color = NULL;
                      ^
[ 50%] Linking CXX shared library libYoloV5.so
[ 50%] Built target YoloV5
Scanning dependencies of target test
[ 75%] Linking CXX executable test
/usr/bin/ld: CMakeFiles/test.dir/test.cpp.o: in function `main':
/home/du/SoftWave/Project/YoloV5-LibTorch/test/test.cpp:49: undefined reference to `cv::imshow(std::string const&, cv::_InputArray const&)'
/usr/bin/ld: ../src/libYoloV5.so: undefined reference to `cv::putText(cv::_InputOutputArray const&, std::string const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
/usr/bin/ld: ../src/libYoloV5.so: undefined reference to `cv::imread(std::string const&, int)'
collect2: error: ld returned 1 exit status
make[3]: *** [test/CMakeFiles/test.dir/build.make:238：test/test] 错误 1
make[2]: *** [CMakeFiles/Makefile2:142：test/CMakeFiles/test.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:149：test/CMakeFiles/test.dir/rule] 错误 2
make: *** [Makefile:182：test] 错误 2

**Comment by garfeng** [comment]
我也遇到了一样的问题，请问是怎么解决的

**Comment by garfeng** [comment]
问题解决：
我出问题的版本是 opencv 4.5.5，后退到 3.4.12 就好了。

**Comment by feizhufanfan** [comment]
> 问题解决： 我出问题的版本是 opencv 4.5.5，后退到 3.4.12 就好了。
一样的 我也是后退opencv版本就好了这个问题我当时查找是因为pytorch预编译包中有Pre-cxx11 ABI与cxx11 ABI两种版本因为开启了pre-cxx11导致opencv中相关的编译参数导致无法通过可以参考这个https://www.jianshu.com/p/6fe9214431c6
与https://michhar.github.io/how-i-built-pytorch-gpu/

**Comment by feizhufanfan** [comment]
> 问题解决： 我出问题的版本是 opencv 4.5.5，后退到 3.4.12 就好了。
一样的 我也是后退opencv版本就好了这个问题我当时查找是因为pytorch预编译包中有Pre-cxx11 ABI与cxx11 ABI两种版本因为开启了pre-cxx11导致opencv中相关的编译参数导致无法通过可以参考这个https://www.jianshu.com/p/6fe9214431c6
与https://michhar.github.io/how-i-built-pytorch-gpu/
